#!/usr/bin/env python3
"""Writes site/data.js for the item wizard: the rules of src/rules.toml and the ids of the existing items.

    python3 tools/site.py

The page reads the rules from this file, so it always follows src/rules.toml. site/verify.js repeats the
checks of tools/check.py; tools/test_site.py compares the two. The GitHub Pages workflow runs this script.

Needs: Python 3.11+.
"""
import datetime
import json
import os
import shutil
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import check

ROOT = check.ROOT


def main():
    rules = check.load_rules()
    db, _ = check.load_db()
    data = {
        "rules": rules,
        "existing": [{"id": k, "name": i.get("name", k)} for k, i in db["items"].items()]
                    + [{"id": k, "name": h.get("name", k)} for k, h in db["hoards"].items()],
        "generated": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
    }
    out = os.path.join(ROOT, "site", "data.js")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write("// Generated by tools/site.py from src/rules.toml and src/cards.toml. Do not edit.\n")
        f.write("window.TOR_DATA = " + json.dumps(data, ensure_ascii=False, indent=1) + ";\n")
    shutil.copyfile(os.path.join(ROOT, "assets", "logo-print.png"), os.path.join(ROOT, "site", "logo.png"))
    print(f"site/data.js: {len(rules['qualities'])} qualities, {len(rules['bases'])} bases, {len(data['existing'])} ids")


if __name__ == "__main__":
    main()
